#

In [4]:
import numpy as np

In [5]:
class HopfieldNetwork:
    def __init__(self, num_neurons):
        self.num_neurons = num_neurons
        self.weights = np.zeros((num_neurons, num_neurons))

    def bi_sigmoid(self,x):
        return (1-np.exp(-x))/(1+np.exp(-x))

    def train(self, vectors):
        # num_vectors = len(vectors)
        for vector in vectors:
            vector = np.reshape(vector, (self.num_neurons, 1))
            self.weights += np.dot(vector, vector.T)
        print("weights : ",self.weights)
        print()
        
    def recall(self, input_vector):
        output=np.dot(self.weights,input_vector)
        output=self.bi_sigmoid(output)
        output=np.sign(output)
        return output

In [6]:
network = HopfieldNetwork(8)

vectors = np.array([[-1, -1, -1, -1, 1, 1, 1, 1],
                    [1, 1, 1, 1, 1, -1, -1, -1],
                    [1, -1, 1, -1, 1, 1, -1, 1],
                    [-1, 1, 1, -1, -1, 1, 1, 1]])
    

network.train(vectors)

vectors = np.array([[-1, -1, -1, -1, 1, 0, 1, 0],
                    [0, 1, 1, 1, 1, -1, -1, -1],
                    [1, -1, 0, -1, 1, 1, -1, 1],
                    [0, 1, 1, -1, -1, 0, 1, 1]])

for vector in vectors:
    output = network.recall(vector)
    print("Input:", vector)
    print("Output:", output)
    print()


weights :  [[ 4.  0.  2.  2.  2. -2. -4. -2.]
 [ 0.  4.  2.  2. -2. -2.  0. -2.]
 [ 2.  2.  4.  0.  0.  0. -2.  0.]
 [ 2.  2.  0.  4.  0. -4. -2. -4.]
 [ 2. -2.  0.  0.  4.  0. -2.  0.]
 [-2. -2.  0. -4.  0.  4.  2.  4.]
 [-4.  0. -2. -2. -2.  2.  4.  2.]
 [-2. -2.  0. -4.  0.  4.  2.  4.]]

Input: [-1 -1 -1 -1  1  0  1  0]
Output: [-1. -1. -1. -1.  1.  1.  1.  1.]

Input: [ 0  1  1  1  1 -1 -1 -1]
Output: [ 1.  1.  1.  1.  1. -1. -1. -1.]

Input: [ 1 -1  0 -1  1  1 -1  1]
Output: [ 1. -1.  1. -1.  1.  1. -1.  1.]

Input: [ 0  1  1 -1 -1  0  1  1]
Output: [-1.  1.  1. -1. -1.  1.  1.  1.]



In [ ]:
# 1.Initialization: Start with setting neuron states randomly or according to input patterns.
# 2.Compute Energy: Calculate network energy based on neuron states and connection weights.
# 3.Update Neurons: Neurons update states simultaneously based on input and connection weights.
    # if the total input to a neuron is positive, 
    # it becomes "on" (+1); if negative, it becomes "off" (-1).
# 4.Repeat: Iterate steps 2 and 3 until the network stabilizes or a set number of iterations is reached.
# 5.Pattern Retrieval: Network converges to nearest stored pattern when given partial or noisy input.
# 6.Stable States: Stable states represent stored patterns or solutions to optimization problems.

In [7]:
# primarily used for associative memory tasks and optimization problems.
# They help remember things and find the best solutions to problems.